name: Deployment pipeline

on:
  push:
    branches:
      - main

#  pull_request:
#    branches: [master]
#    types: [opened, synchronize]

jobs:
  deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - run: echo "Hello World"
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.19.1'

      - name: Install dependencies
        run: npm install

      - name: lint
        run: npm run lint

      - name: build
        run: npm run build

      - name: test
        run: npm run test

      - name: setup deploy
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: setup db
        run: flyctl secrets set PERSONS_DB_URI="${{ secrets.PERSONS_DB_URI }}" --stage
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: deploy
        if: ${{ github.event_name == 'push' }}
        run: flyctl deploy --remote-only --wait-timeout 60
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: rollback
        if: failure()
        shell: bash
        run: .github/scripts/rollback.sh
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  tag_release:
    needs: [deployment_pipeline]
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.sha }} # required for better experience using pre-releases
          fetch-depth: '0'

      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' }}
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: minor
          WITH_V: true

#  notify_deploy_success:
#    needs: [ tag_release ]
#    runs-on: ubuntu-20.04
#    steps:
#      - name: Notify success
#        uses: rjstone/discord-webhook-notify@v1.0.4
#        if: ${{ github.event_name == 'push' }}
#        with:
#          severity: info
#          text: A new version of Pokedex deployed
#          description: to https://cold-star-519.fly.dev/ by ${{ github.event.pusher.name }}
#          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}


